import type { Metadata } from "next";
import { Source_Sans_3 } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { notFound } from 'next/navigation';
import { routing } from '../../i18n/routing';

import CookieConsent from "./components/landing/CookieConsent";
import { CSPostHogProvider } from "./providers";

const sourceSans3 = Source_Sans_3({
  subsets: ["latin"],
  variable: "--font-source-sans-3",
});

export const metadata: Metadata = {
  title: "Verdyct",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  // Ensure that the incoming `locale` is valid
  // await params is required in Next.js 15+
  const { locale } = await params;
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={`${sourceSans3.variable} antialiased`}>
        <NextIntlClientProvider messages={messages}>
          <CSPostHogProvider>
            {children}
            <CookieConsent />
          </CSPostHogProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}